[connections.ci]
account = "${SNOWFLAKE_ACCOUNT}"
user = "${SNOWFLAKE_USER}"
password = "${SNOWFLAKE_PASSWORD}"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "ECOM_ANALYTICS"
schema = "DBT_DEV"
